# FFmpeg macOS ARM64 (LGPL) + whisper filter (via whisper.cpp XCFramework)
# Static FFmpeg (no external dylibs to ship), ready to bundle into a .app
name: build-ffmpeg-macos-arm64-lgpl-whisper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FFMPEG_TAG: "n8.0"
  INSTALL_PREFIX: "${{ github.workspace }}/install"
  WHISPER_PREFIX: "${{ github.workspace }}/whisper-install"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

jobs:
  build-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies (idempotent)
        run: |
          set -euxo pipefail
          export HOMEBREW_NO_AUTO_UPDATE=1
          ensure () { if brew list --versions "$1" >/dev/null 2>&1; then echo "✓ $1 already installed"; else brew install "$1"; fi }
          ensure cmake
          ensure ninja
          ensure pkg-config
          ensure nasm
          ensure yasm
          ensure libvpx
          ensure aom
          ensure opus
          ensure libvorbis
          ensure libogg

      - name: Download and setup whisper.cpp XCFramework (macOS arm64 only)
        run: |
          set -euxo pipefail

          mkdir -p "$WHISPER_PREFIX/lib" "$WHISPER_PREFIX/include" "$WHISPER_PREFIX/lib/pkgconfig"

          curl -L -o whisper-xcframework.zip \
            "https://github.com/ggml-org/whisper.cpp/releases/download/v1.7.6/whisper-v1.7.6-xcframework.zip"
          unzip -q whisper-xcframework.zip

          # Найдём путь к XCFramework
          XCFRAMEWORK=$(find . -maxdepth 2 -type d -name "*.xcframework" | head -1)
          echo "XCFRAMEWORK = $XCFRAMEWORK"

          # Точный срез под macOS ARM64 (обычно каталог называется 'macos-arm64')
          MACOS_ARM_DIR=$(find "$XCFRAMEWORK" -type d -name "macos-arm64" | head -1)
          if [ -z "$MACOS_ARM_DIR" ]; then
            echo "❌ macos-arm64 slice not found in XCFramework"
            exit 1
          fi
          echo "Using slice: $MACOS_ARM_DIR"

          # Копируем заголовки и именно arm64-библиотеки
          # (внутри среза обычно лежат include/whisper.h и lib*.a)
          if [ -d "$MACOS_ARM_DIR/Headers" ]; then
            cp -v "$MACOS_ARM_DIR/Headers/"*.h "$WHISPER_PREFIX/include/" || true
          fi
          # Иногда заголовки лежат уровнем выше:
          find "$XCFRAMEWORK" -maxdepth 3 -name "whisper.h" -exec cp -v {} "$WHISPER_PREFIX/include/" \; || true
          find "$XCFRAMEWORK" -maxdepth 3 -name "ggml.h"    -exec cp -v {} "$WHISPER_PREFIX/include/" \; || true

          # Копируем только arm64 статические библиотеки
          find "$MACOS_ARM_DIR" -maxdepth 2 -name "lib*.a" -exec cp -v {} "$WHISPER_PREFIX/lib/" \;

          echo "=== Installed headers ==="
          ls -la "$WHISPER_PREFIX/include" || true
          echo "=== Installed libs ==="
          ls -la "$WHISPER_PREFIX/lib"

          # Создаём корректный whisper.pc для pkg-config
          cat > "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc" <<'PC'
          prefix=@PREFIX@
          exec_prefix=${prefix}
          libdir=${prefix}/lib
          includedir=${prefix}/include

          Name: whisper
          Description: whisper.cpp C API (macOS arm64, XCFramework)
          Version: 1.7.6
          # В Libs укажем всё, что нужно линковщику во время configure (не только Libs.private),
          # иначе тест линковки у FFmpeg может провалиться.
          Libs: -L${libdir} -lwhisper -lggml -lggml-metal -lggml-base -framework Metal -framework MetalKit -framework Foundation -framework Accelerate -lc++ -lpthread
          Cflags: -I${includedir}
          PC
          sed -i '' "s|@PREFIX@|$WHISPER_PREFIX|g" "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc"

          echo "=== PKG-CONFIG test ==="
          export PKG_CONFIG_PATH="$WHISPER_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          pkg-config --exists whisper && echo "✅ whisper.pc found"
          pkg-config --modversion whisper
          pkg-config --cflags whisper
          pkg-config --libs whisper

      - name: Build FFmpeg (LGPL, static, +whisper)
        env:
          PKG_CONFIG_PATH: "${{ env.WHISPER_PREFIX }}/lib/pkgconfig:${{ env.PKG_CONFIG_PATH }}"
        run: |
          set -euxo pipefail
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-src
          cd ffmpeg-src
          git checkout "$FFMPEG_TAG"

          export MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET

          # Статическая сборка FFmpeg: проще вкладывать в .app, нет зависимости от brew .dylib на машинах пользователей
          ./configure \
            --prefix="$INSTALL_PREFIX" \
            --arch=arm64 \
            --target-os=darwin \
            --enable-whisper \
            --enable-videotoolbox \
            --disable-gpl \
            --disable-nonfree \
            --enable-static \
            --disable-shared \
            --enable-libvpx \
            --enable-libaom \
            --enable-libopus \
            --enable-libvorbis \
            --disable-debug \
            --disable-doc \
            --enable-pic

          make -j"$(sysctl -n hw.ncpu)"
          make install

      - name: Verify build and LGPL compliance
        run: |
          set -euxo pipefail
          "$INSTALL_PREFIX/bin/ffmpeg" -version
          "$INSTALL_PREFIX/bin/ffmpeg" -filters | grep whisper
          # Проверяем, что нет GPL
          ! "$INSTALL_PREFIX/bin/ffmpeg" -buildconf | grep -q -- "--enable-gpl"
          echo "✅ LGPL (no --enable-gpl)"
          echo "=== Linked libs (should be mostly system frameworks) ==="
          otool -L "$INSTALL_PREFIX/bin/ffmpeg" | sed -n '1,120p'

      - name: Package for Flutter (.tar.gz with ffmpeg + ffprobe only)
        run: |
          set -euxo pipefail
          cd "$INSTALL_PREFIX"
          tar -czf ffmpeg-macos-arm64-lgpl-whisper.tar.gz \
            bin/ffmpeg bin/ffprobe
          echo "=== Package contents ==="
          tar -tzf ffmpeg-macos-arm64-lgpl-whisper.tar.gz
          ls -lh ffmpeg-macos-arm64-lgpl-whisper.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64-lgpl-whisper
          path: ${{ env.INSTALL_PREFIX }}/ffmpeg-macos-arm64-lgpl-whisper.tar.gz
