# FFmpeg macOS ARM64 build for Flutter integration
# Builds shared libraries (.dylib) for use with dart:ffi
name: build-ffmpeg-macos-arm64-lgpl-whisper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FFMPEG_TAG: "n8.0"
  INSTALL_PREFIX: "${{ github.workspace }}/install"
  WHISPER_PREFIX: "${{ github.workspace }}/whisper-install"

jobs:
  build-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps (arm64)
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew tap homebrew/core
          brew install cmake ninja pkg-config nasm yasm libvpx aom opus libvorbis libogg

      - name: Build & install whisper.cpp (arm64, static lib + pkg-config)
        run: |
          set -eux
          
          # Clone whisper.cpp
          git clone --depth=1 https://github.com/ggml-org/whisper.cpp
          cd whisper.cpp
          
          # Get actual version from CMakeLists.txt
          WHISPER_VERSION=$(grep -E "set\(WHISPER_VERSION" CMakeLists.txt | cut -d'"' -f2 || echo "1.8.0")
          echo "Detected whisper version: $WHISPER_VERSION"
          cd ..
          
          # Build whisper.cpp
          cmake -S whisper.cpp -B build-whisper \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$WHISPER_PREFIX" \
                -DBUILD_SHARED_LIBS=OFF \
                -DWHISPER_BUILD_TESTS=OFF \
                -DWHISPER_BUILD_EXAMPLES=OFF
          cmake --build build-whisper --config Release --parallel
          cmake --install build-whisper
          
          # Verify installation
          echo "=== Whisper installation verification ==="
          ls -la "$WHISPER_PREFIX/lib/" || true
          ls -la "$WHISPER_PREFIX/include/" || true
          
          # Ensure headers are present
          mkdir -p "$WHISPER_PREFIX/include"
          cp -f whisper.cpp/whisper.h "$WHISPER_PREFIX/include/" || true
          cp -f whisper.cpp/ggml.h "$WHISPER_PREFIX/include/" || true
          
          # Create pkg-config file
          mkdir -p "$WHISPER_PREFIX/lib/pkgconfig"
          cat > "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc" <<PC
prefix=$WHISPER_PREFIX
exec_prefix=\${prefix}
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: whisper
Description: whisper.cpp C API
Version: $WHISPER_VERSION
Libs: -L\${libdir} -lwhisper
Libs.private: -framework Accelerate -lpthread
Cflags: -I\${includedir}
PC
          
          # Verify pkg-config file
          echo "=== PKG-CONFIG verification ==="
          cat "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc"
          export PKG_CONFIG_PATH="$WHISPER_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          pkg-config --exists whisper && echo "whisper pkg-config: OK" || echo "whisper pkg-config: FAILED"
          pkg-config --modversion whisper || echo "Cannot get whisper version"
          pkg-config --libs whisper || echo "Cannot get whisper libs"

      - name: Build FFmpeg (arm64, LGPL, +whisper)
        run: |
          set -eux
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-src
          cd ffmpeg-src && git checkout "$FFMPEG_TAG"
          
          # Initialize and set PKG_CONFIG_PATH properly
          export PKG_CONFIG_PATH="$WHISPER_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          
          # Verify whisper is available
          pkg-config --exists whisper || { echo "ERROR: whisper not found via pkg-config"; exit 1; }
          pkg-config --modversion whisper
          pkg-config --libs whisper
          
          ./configure \
            --prefix="$INSTALL_PREFIX" \
            --arch=arm64 --target-os=darwin \
            --enable-whisper \
            --enable-videotoolbox \
            --disable-gpl --disable-nonfree \
            --disable-static --enable-shared \
            --enable-libvpx --enable-libaom \
            --enable-libopus --enable-libvorbis \
            --disable-debug \
            --disable-doc \
            --disable-programs \
            --enable-ffmpeg --enable-ffprobe \
            --enable-pic
          make -j"$(sysctl -n hw.ncpu)"
          make install
          
          # Verify LGPL compliance
          echo "=== Verifying LGPL compliance ==="
          "$INSTALL_PREFIX/bin/ffmpeg" -version
          "$INSTALL_PREFIX/bin/ffmpeg" -filters | grep whisper
          echo "=== Checking build configuration (should NOT contain GPL) ==="
          "$INSTALL_PREFIX/bin/ffmpeg" -buildconf
          if "$INSTALL_PREFIX/bin/ffmpeg" -buildconf | grep -q -- "--enable-gpl"; then
            echo "ERROR: GPL found in build configuration!"
            exit 1
          fi
          echo "=== Checking dynamic libraries ==="
          ls -la "$INSTALL_PREFIX/lib/"*.dylib
          otool -L "$INSTALL_PREFIX/bin/ffmpeg"
          echo "=== LGPL verification passed ==="

      - name: Package ARM64 binaries and libraries
        run: |
          cd "$INSTALL_PREFIX"
          # Package both binaries and shared libraries for Flutter
          tar -czf ffmpeg-macos-arm64-lgpl-whisper.tar.gz \
            bin/ffmpeg bin/ffprobe \
            lib/*.dylib \
            include/
          ls -lh ffmpeg-macos-arm64-lgpl-whisper.tar.gz
          echo "=== Contents ==="
          tar -tzf ffmpeg-macos-arm64-lgpl-whisper.tar.gz

      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64-lgpl-whisper
          path: ${{ env.INSTALL_PREFIX }}/ffmpeg-macos-arm64-lgpl-whisper.tar.gz
