name: build-ffmpeg-macos-arm64-lgpl-whisper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FFMPEG_TAG: "n8.0"
  INSTALL_PREFIX: "${{ github.workspace }}/install"
  WHISPER_PREFIX: "${{ github.workspace }}/whisper-install"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

jobs:
  build-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies (idempotent)
        run: |
          set -euxo pipefail
          export HOMEBREW_NO_AUTO_UPDATE=1
          ensure () { if brew list --versions "$1" >/dev/null 2>&1; then echo "✓ $1 already installed"; else brew install "$1"; fi }
          ensure cmake
          ensure ninja
          ensure pkg-config
          ensure nasm
          ensure yasm
          ensure libvpx
          ensure aom
          ensure opus
          ensure libvorbis
          ensure libogg

      - name: Download and setup whisper.cpp XCFramework (macOS slice)
        run: |
          set -euxo pipefail
          mkdir -p "$WHISPER_PREFIX/Frameworks" "$WHISPER_PREFIX/lib/pkgconfig"

          # 1) Download official XCFramework
          curl -L -o whisper-xcframework.zip \
            "https://github.com/ggml-org/whisper.cpp/releases/download/v1.7.6/whisper-v1.7.6-xcframework.zip"
          unzip -q whisper-xcframework.zip

          # 2) Locate XCFramework and macOS slice (usually "macos-arm64_x86_64" or similar)
          XCFRAMEWORK=$(find . -maxdepth 3 -type d -name "whisper.xcframework" | head -1)
          echo "XCFRAMEWORK = $XCFRAMEWORK"

          MACOS_DIR=$(find "$XCFRAMEWORK" -maxdepth 2 -type d -name "macos*" | head -1)
          if [ -z "${MACOS_DIR:-}" ]; then
            echo "❌ macOS slice not found in XCFramework"
            find "$XCFRAMEWORK" -maxdepth 2 -type d -print
            exit 1
          fi
          echo "Using macOS slice: $MACOS_DIR"

          # 3) Copy whisper.framework for macOS into our prefix
          if [ ! -d "$MACOS_DIR/whisper.framework" ]; then
            echo "❌ whisper.framework not found in macOS slice"
            find "$MACOS_DIR" -maxdepth 2 -print
            exit 1
          fi
          cp -R "$MACOS_DIR/whisper.framework" "$WHISPER_PREFIX/Frameworks/"

          # 4) Headers path inside the framework
          ln -sf "../Frameworks/whisper.framework/Headers" "$WHISPER_PREFIX/include" || true

          # 5) Create pkg-config file that points to the framework
          cat > "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc" <<'PC'
          prefix=@PREFIX@
          exec_prefix=${prefix}
          frameworkdir=${prefix}/Frameworks
          includedir=${frameworkdir}/whisper.framework/Headers

          Name: whisper
          Description: whisper.cpp (XCFramework, macOS)
          Version: 1.7.6
          Libs: -F${frameworkdir} -framework whisper -framework Metal -framework MetalKit -framework Foundation -framework Accelerate -lc++ -lpthread
          Cflags: -I${includedir}
          PC
          sed -i '' "s|@PREFIX@|$WHISPER_PREFIX|g" "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc"

          # 6) Sanity check
          export PKG_CONFIG_PATH="$WHISPER_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          pkg-config --exists whisper
          pkg-config --modversion whisper
          pkg-config --libs whisper
          pkg-config --cflags whisper

      - name: Build FFmpeg (LGPL, static, +whisper)
        env:
          PKG_CONFIG_PATH: "${{ env.WHISPER_PREFIX }}/lib/pkgconfig:${{ env.PKG_CONFIG_PATH }}"
        run: |
          set -euxo pipefail
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-src
          cd ffmpeg-src
          git checkout "$FFMPEG_TAG"

          export MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET

          ./configure \
            --prefix="$INSTALL_PREFIX" \
            --arch=arm64 \
            --target-os=darwin \
            --enable-whisper \
            --enable-videotoolbox \
            --disable-gpl \
            --disable-nonfree \
            --enable-static \
            --disable-shared \
            --enable-libvpx \
            --enable-libaom \
            --enable-libopus \
            --enable-libvorbis \
            --disable-debug \
            --disable-doc \
            --enable-pic

          make -j"$(sysctl -n hw.ncpu)"
          make install

      - name: Verify build and LGPL compliance
        run: |
          set -euxo pipefail
          "$INSTALL_PREFIX/bin/ffmpeg" -version
          "$INSTALL_PREFIX/bin/ffmpeg" -filters | grep whisper
          ! "$INSTALL_PREFIX/bin/ffmpeg" -buildconf | grep -q -- "--enable-gpl"
          echo "✅ LGPL (no --enable-gpl)"
          echo "=== Linked libs (ffmpeg) ==="
          otool -L "$INSTALL_PREFIX/bin/ffmpeg" | sed -n '1,120p'

      - name: Package for Flutter (.tar.gz with ffmpeg + ffprobe)
        run: |
          set -euxo pipefail
          cd "$INSTALL_PREFIX"
          tar -czf ffmpeg-macos-arm64-lgpl-whisper.tar.gz \
            bin/ffmpeg bin/ffprobe
          echo "=== Package contents ==="
          tar -tzf ffmpeg-macos-arm64-lgpl-whisper.tar.gz
          ls -lh ffmpeg-macos-arm64-lgpl-whisper.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64-lgpl-whisper
          path: ${{ env.INSTALL_PREFIX }}/ffmpeg-macos-arm64-lgpl-whisper.tar.gz
