name: build-ffmpeg-macos-arm64-lgpl-whisper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FFMPEG_TAG: "n8.0"
  INSTALL_PREFIX: "${{ github.workspace }}/install"
  WHISPER_PREFIX: "${{ github.workspace }}/whisper-install"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

jobs:
  build-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies (idempotent)
        run: |
          set -euxo pipefail
          export HOMEBREW_NO_AUTO_UPDATE=1
          ensure () { if brew list --versions "$1" >/dev/null 2>&1; then echo "✓ $1 already installed"; else brew install "$1"; fi }
          ensure cmake
          ensure ninja
          ensure pkg-config
          ensure nasm
          ensure yasm
          ensure libvpx
          ensure aom
          ensure opus
          ensure libvorbis
          ensure libogg

      - name: Build and install whisper.cpp (local prefix, Metal ON, BLAS OFF)
        run: |
          set -eux
          git clone --depth=1 https://github.com/ggml-org/whisper.cpp
          cmake -S whisper.cpp -B build-whisper \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="$WHISPER_PREFIX" \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET \
                -DBUILD_SHARED_LIBS=OFF \
                -DGGML_METAL=ON \
                -DGGML_BLAS=OFF \
                -DWHISPER_BUILD_TESTS=OFF \
                -DWHISPER_BUILD_EXAMPLES=OFF
          cmake --build build-whisper --config Release --parallel
          cmake --install build-whisper

          # minimal whisper.pc (иногда upstream не кладёт)
          mkdir -p "$WHISPER_PREFIX/lib/pkgconfig" "$WHISPER_PREFIX/include"
          cp -f whisper.cpp/whisper.h "$WHISPER_PREFIX/include/" || true
          cat > "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc" <<'PC'
          prefix=@PREFIX@
          exec_prefix=${prefix}
          libdir=${prefix}/lib
          includedir=${prefix}/include
          Name: whisper
          Description: whisper.cpp C API
          Version: 1.7.5
          Libs: -L${libdir} -lwhisper -framework Metal -framework MetalKit -framework Foundation -framework Accelerate -lpthread
          Cflags: -I${includedir}
          PC
          sed -i '' "s|@PREFIX@|$WHISPER_PREFIX|g" "$WHISPER_PREFIX/lib/pkgconfig/whisper.pc"

          # Проверка pkg-config
          export PKG_CONFIG_PATH="$WHISPER_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          pkg-config --exists whisper
          pkg-config --modversion whisper

      - name: Build FFmpeg (LGPL, shared, +whisper)
        env:
          PKG_CONFIG_PATH: "${{ env.WHISPER_PREFIX }}/lib/pkgconfig"
        run: |
          set -eux
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-src
          cd ffmpeg-src
          git checkout "$FFMPEG_TAG"

          export MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET

          ./configure \
            --prefix="$INSTALL_PREFIX" \
            --arch=arm64 \
            --target-os=darwin \
            --enable-whisper \
            --enable-videotoolbox \
            --disable-gpl \
            --disable-nonfree \
            --disable-static \
            --enable-shared \
            --enable-libvpx \
            --enable-libaom \
            --enable-libopus \
            --enable-libvorbis \
            --disable-debug \
            --disable-doc \
            --enable-pic

          make -j"$(sysctl -n hw.ncpu)"
          make install

      - name: Verify build and LGPL compliance
        run: |
          set -eux
          "$INSTALL_PREFIX/bin/ffmpeg" -version
          "$INSTALL_PREFIX/bin/ffmpeg" -filters | grep whisper
          ! "$INSTALL_PREFIX/bin/ffmpeg" -buildconf | grep -q -- "--enable-gpl"
          otool -L "$INSTALL_PREFIX/bin/ffmpeg" | sed -n '1,60p'

      - name: Package for Flutter (bins + dylibs + headers)
        run: |
          set -eux
          cd "$INSTALL_PREFIX"
          tar -czf ffmpeg-macos-arm64-lgpl-whisper.tar.gz \
            bin/ffmpeg bin/ffprobe lib/*.dylib include || true
          tar -tzf ffmpeg-macos-arm64-lgpl-whisper.tar.gz | sed -n '1,200p'
          ls -lh ffmpeg-macos-arm64-lgpl-whisper.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-arm64-lgpl-whisper
          path: ${{ env.INSTALL_PREFIX }}/ffmpeg-macos-arm64-lgpl-whisper.tar.gz
